---
version: '3.0'

services:
  db:
    image: postgres:13.0
    restart: always
    env_file:
      - env_files/postgres-credentials.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-internal

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - backend-internal

  backend:
    build:
      dockerfile: server/Dockerfile
      context: .
    image: "altklausur_ausleihe-backend:latest"
    restart: always
    ports:
      - "127.0.0.1:3090:8081"
    env_file:
      - env_files/postgres-credentials.env
      - env_files/minio.env
      - env_files/backend.env
    networks:
      - backend-internal
      - backend
    depends_on:
      - db

  exam_marker:
    build:
      dockerfile: exam_marker/Dockerfile
      context: .
    image: "altklausur_ausleihe-exam_marker:latest"
    restart: always
    env_file:
      - env_files/postgres-credentials.env
      - env_files/minio.env
      - env_files/exam_marker.env
    networks:
      - backend-internal
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: frontend
      args:
        SERVER_HTTP: https://altklausuren.mathphys.info/query
        SERVER_WS: wss://altklausuren.mathphys.info/query
        NGINX_CONFIG_NAME: nginx-prod.conf
    image: "altklausur_ausleihe-frontend:latest"
    restart: always
    ports:
      - "127.0.0.1:3091:80"
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend-internal: {}
  backend: {}

volumes:
  db: {}
