---
version: '3.0'

services:
  db:
    image: postgres:13.0
    env_file:
      - env_files/postgres-credentials.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-internal

  redis:
    image: "redis:alpine"
    networks:
      - backend-internal

  storage:
    image: quay.io/minio/minio:RELEASE.2022-03-14T18-25-24Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - env_files/minio.env
    volumes:
      - storage:/data
    networks:
      - backend-internal

  backend:
    build:
      dockerfile: server/Dockerfile
      context: .
    image: "altklausur_ausleihe-backend:latest"
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - env_files/postgres-credentials.env
      - env_files/minio.env
      - env_files/backend.env
    networks:
      - backend-internal
      - backend
    depends_on:
      - db
      - storage

  exam_marker:
    build:
      dockerfile: exam_marker/Dockerfile
      context: .
    image: "altklausur_ausleihe-exam_marker:latest"
    env_file:
      - env_files/postgres-credentials.env
      - env_files/minio.env
      - env_files/exam_marker.env
    networks:
      - backend-internal
    depends_on:
      - db
      - storage
      - redis

  frontend:
    build:
      context: frontend
      args:
        SERVER_HTTP: http://localhost:8080/query
        SERVER_WS: ws://localhost:8081/query
        NGINX_CONFIG_NAME: nginx.conf
    image: "altklausur_ausleihe-frontend:latest"
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend-internal: {}
  backend: {}

volumes:
  db: {}
  storage: {}
