// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Exam struct {
	ID       string      `json:"id"`
	Subject  string      `json:"subject"`
	URL      string      `json:"url"`
	Examiner []*Lecturer `json:"examiner"`
	Semester *string     `json:"semester"`
}

type Lecturer struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

type LinkInput struct {
	LecturerID string `json:"lecturer_id"`
	ExamID     string `json:"exam_id"`
}

type NewExam struct {
	Subject  string  `json:"subject"`
	Semester *string `json:"semester"`
}

type NewLecturer struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
