// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PresignedReturn struct {
	ViewURL     string `json:"viewUrl"`
	DownloadURL string `json:"downloadUrl"`
}

type Query struct {
}
